apiVersion: v1
kind: Service
metadata:
  name: {{ include "echophase.fullname" . }}
  labels:
    {{- include "echophase.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.echophase.service.type }}
  ports:
  - port: {{ .Values.echophase.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "echophase.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
