apiVersion: v1
kind: Secret
metadata:
  name: {{ include "echophase.fullname" . }}-secrets
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "echophase.labels" . | nindent 4 }}
type: Opaque
stringData:
  # PostgreSQL
  POSTGRES_HOST: {{ printf "%s-postgres" (include "echophase.fullname" .) | quote }}
  POSTGRES_PORT: {{ .Values.postgres.service.port | quote }}
  POSTGRES_USER: {{ .Values.secrets.POSTGRES_USER | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD | quote }}
  POSTGRES_DB: {{ .Values.secrets.POSTGRES_DB | quote }}
  
  # Valkey
  VALKEY_HOST: {{ printf "%s-valkey" (include "echophase.fullname" .) | quote }}
  VALKEY_PORT: {{ .Values.valkey.service.port | quote }}
  VALKEY_PASSWORD: {{ .Values.secrets.VALKEY_PASSWORD | quote }}
  
  # ScyllaDB
  SCYLLA_CLUSTER_NAME: {{ .Values.scylla.clusterName | quote }}
  SCYLLA_CONTACT_POINT: {{ printf "%s-scylla" (include "echophase.fullname" .) | quote }}
  SCYLLA_SEEDS: {{ printf "%s-scylla" (include "echophase.fullname" .) | quote }}
  SCYLLA_AUTO_BOOTSTRAP: {{ .Values.scylla.autoBootstrap | quote }}
  SCYLLA_USERNAME: {{ .Values.secrets.SCYLLA_USERNAME | quote }}
  SCYLLA_PASSWORD: {{ .Values.secrets.SCYLLA_PASSWORD | quote }}
  SCYLLA_KEYSPACE: {{ .Values.scylla.keyspace | quote }}
