services:
  echophase:
    image: localhost:5000/echophase:latest
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    volumes:
      - logs:/app/Logs
    networks:
      - echonet
    healthcheck:
      test: ["CMD", "dotnet", "EchoPhase.dll", "healthcheck"]
      interval: 5s
      timeout: 3s
      retries: 5
    depends_on:
      echophase-migrate:
        condition: service_completed_successfully

  echophase-frontend:
    image: localhost:5000/echophase-frontend:latest
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - echonet
    depends_on:
      echophase:
        condition: service_healthy

  echophase-migrate:
    image: localhost:5000/echophase:latest
    command: [ "migrate" ]
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
      valkey:
        condition: service_healthy
      scylla:
        condition: service_healthy
    networks:
      - echonet
    restart: "no"

  valkey:
    image: valkey/valkey:latest
    restart: unless-stopped
    env_file:
      - ./.env
    command: ["valkey-server", "--requirepass", "${VALKEY_PASSWORD}"]
    volumes:
      - valkey-data:/data
    networks:
      - echonet
    healthcheck:
      test: ["CMD", "valkey-cli", "-a", "${VALKEY_PASSWORD}", "PING"]
      interval: 5s
      timeout: 3s
      retries: 5

  postgres:
    image: postgres:17
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - echonet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  scylla:
    image: scylladb/scylla:latest
    restart: unless-stopped
    env_file:
      - ./.env
    networks:
      - echonet
    volumes:
      - scylla-data:/var/lib/scylla
    healthcheck:
      test: ["CMD", "cqlsh", "-u", "${SCYLLA_USERNAME:-cassandra}", "-p", "${SCYLLA_PASSWORD:-cassandra}", "-e", "describe keyspaces"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  echonet:
    driver: bridge

volumes:
  logs:
  valkey-data:
  postgres-data:
  scylla-data:
