services:
  echophase:
    image: localhost:5000/echophase:latest
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://0.0.0.0:8080
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/Logs
    networks:
      - echonet
    depends_on:
      echophase-migrate:
        condition: service_completed_successfully

  echophase-migrate:
    image: localhost:5000/echophase:latest
    command: [ "migrate" ]
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
      valkey:
        condition: service_healthy
    networks:
      - echonet
    restart: "no"

  valkey:
    image: valkey/valkey:latest
    restart: unless-stopped
    env_file:
      - ./.env
    command: ["valkey-server", "--requirepass", "${VALKEY_PASSWORD}"]
    volumes:
      - ./valkey:/data
    networks:
      - echonet
    healthcheck:
      test: ["CMD", "valkey-cli", "-a", "${VALKEY_PASSWORD}", "PING"]
      interval: 5s
      timeout: 3s
      retries: 5

  postgres:
    image: postgres:17
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - echonet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  echonet:
    driver: bridge
