/**
 * @fileoverview gRPC-Web generated client stub for DiscordToken
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.20.3
// source: discord_token.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as discord_token_pb from './discord_token_pb'; // proto import: "discord_token.proto"


export class DiscordTokenGrpcServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGet = new grpcWeb.MethodDescriptor(
    '/DiscordToken.DiscordTokenGrpcService/Get',
    grpcWeb.MethodType.UNARY,
    discord_token_pb.DiscordTokenSearchOptionsGrpc,
    discord_token_pb.DiscordTokenListGrpc,
    (request: discord_token_pb.DiscordTokenSearchOptionsGrpc) => {
      return request.serializeBinary();
    },
    discord_token_pb.DiscordTokenListGrpc.deserializeBinary
  );

  get(
    request: discord_token_pb.DiscordTokenSearchOptionsGrpc,
    metadata?: grpcWeb.Metadata | null): Promise<discord_token_pb.DiscordTokenListGrpc>;

  get(
    request: discord_token_pb.DiscordTokenSearchOptionsGrpc,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: discord_token_pb.DiscordTokenListGrpc) => void): grpcWeb.ClientReadableStream<discord_token_pb.DiscordTokenListGrpc>;

  get(
    request: discord_token_pb.DiscordTokenSearchOptionsGrpc,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: discord_token_pb.DiscordTokenListGrpc) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/DiscordToken.DiscordTokenGrpcService/Get',
        request,
        metadata || {},
        this.methodDescriptorGet,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/DiscordToken.DiscordTokenGrpcService/Get',
    request,
    metadata || {},
    this.methodDescriptorGet);
  }

  methodDescriptorCreate = new grpcWeb.MethodDescriptor(
    '/DiscordToken.DiscordTokenGrpcService/Create',
    grpcWeb.MethodType.UNARY,
    discord_token_pb.DiscordTokenGrpc,
    discord_token_pb.DiscordTokenGrpc,
    (request: discord_token_pb.DiscordTokenGrpc) => {
      return request.serializeBinary();
    },
    discord_token_pb.DiscordTokenGrpc.deserializeBinary
  );

  create(
    request: discord_token_pb.DiscordTokenGrpc,
    metadata?: grpcWeb.Metadata | null): Promise<discord_token_pb.DiscordTokenGrpc>;

  create(
    request: discord_token_pb.DiscordTokenGrpc,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: discord_token_pb.DiscordTokenGrpc) => void): grpcWeb.ClientReadableStream<discord_token_pb.DiscordTokenGrpc>;

  create(
    request: discord_token_pb.DiscordTokenGrpc,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: discord_token_pb.DiscordTokenGrpc) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/DiscordToken.DiscordTokenGrpcService/Create',
        request,
        metadata || {},
        this.methodDescriptorCreate,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/DiscordToken.DiscordTokenGrpcService/Create',
    request,
    metadata || {},
    this.methodDescriptorCreate);
  }

  methodDescriptorCreateBatch = new grpcWeb.MethodDescriptor(
    '/DiscordToken.DiscordTokenGrpcService/CreateBatch',
    grpcWeb.MethodType.UNARY,
    discord_token_pb.DiscordTokenListGrpc,
    discord_token_pb.DiscordTokenResultGrpc,
    (request: discord_token_pb.DiscordTokenListGrpc) => {
      return request.serializeBinary();
    },
    discord_token_pb.DiscordTokenResultGrpc.deserializeBinary
  );

  createBatch(
    request: discord_token_pb.DiscordTokenListGrpc,
    metadata?: grpcWeb.Metadata | null): Promise<discord_token_pb.DiscordTokenResultGrpc>;

  createBatch(
    request: discord_token_pb.DiscordTokenListGrpc,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: discord_token_pb.DiscordTokenResultGrpc) => void): grpcWeb.ClientReadableStream<discord_token_pb.DiscordTokenResultGrpc>;

  createBatch(
    request: discord_token_pb.DiscordTokenListGrpc,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: discord_token_pb.DiscordTokenResultGrpc) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/DiscordToken.DiscordTokenGrpcService/CreateBatch',
        request,
        metadata || {},
        this.methodDescriptorCreateBatch,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/DiscordToken.DiscordTokenGrpcService/CreateBatch',
    request,
    metadata || {},
    this.methodDescriptorCreateBatch);
  }

  methodDescriptorEdit = new grpcWeb.MethodDescriptor(
    '/DiscordToken.DiscordTokenGrpcService/Edit',
    grpcWeb.MethodType.UNARY,
    discord_token_pb.EditRequestGrpc,
    discord_token_pb.DiscordTokenGrpc,
    (request: discord_token_pb.EditRequestGrpc) => {
      return request.serializeBinary();
    },
    discord_token_pb.DiscordTokenGrpc.deserializeBinary
  );

  edit(
    request: discord_token_pb.EditRequestGrpc,
    metadata?: grpcWeb.Metadata | null): Promise<discord_token_pb.DiscordTokenGrpc>;

  edit(
    request: discord_token_pb.EditRequestGrpc,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: discord_token_pb.DiscordTokenGrpc) => void): grpcWeb.ClientReadableStream<discord_token_pb.DiscordTokenGrpc>;

  edit(
    request: discord_token_pb.EditRequestGrpc,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: discord_token_pb.DiscordTokenGrpc) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/DiscordToken.DiscordTokenGrpcService/Edit',
        request,
        metadata || {},
        this.methodDescriptorEdit,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/DiscordToken.DiscordTokenGrpcService/Edit',
    request,
    metadata || {},
    this.methodDescriptorEdit);
  }

  methodDescriptorEditBatch = new grpcWeb.MethodDescriptor(
    '/DiscordToken.DiscordTokenGrpcService/EditBatch',
    grpcWeb.MethodType.UNARY,
    discord_token_pb.EditBatchRequestGrpc,
    discord_token_pb.DiscordTokenResultGrpc,
    (request: discord_token_pb.EditBatchRequestGrpc) => {
      return request.serializeBinary();
    },
    discord_token_pb.DiscordTokenResultGrpc.deserializeBinary
  );

  editBatch(
    request: discord_token_pb.EditBatchRequestGrpc,
    metadata?: grpcWeb.Metadata | null): Promise<discord_token_pb.DiscordTokenResultGrpc>;

  editBatch(
    request: discord_token_pb.EditBatchRequestGrpc,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: discord_token_pb.DiscordTokenResultGrpc) => void): grpcWeb.ClientReadableStream<discord_token_pb.DiscordTokenResultGrpc>;

  editBatch(
    request: discord_token_pb.EditBatchRequestGrpc,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: discord_token_pb.DiscordTokenResultGrpc) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/DiscordToken.DiscordTokenGrpcService/EditBatch',
        request,
        metadata || {},
        this.methodDescriptorEditBatch,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/DiscordToken.DiscordTokenGrpcService/EditBatch',
    request,
    metadata || {},
    this.methodDescriptorEditBatch);
  }

  methodDescriptorDelete = new grpcWeb.MethodDescriptor(
    '/DiscordToken.DiscordTokenGrpcService/Delete',
    grpcWeb.MethodType.UNARY,
    discord_token_pb.DiscordTokenGrpc,
    discord_token_pb.DiscordTokenGrpc,
    (request: discord_token_pb.DiscordTokenGrpc) => {
      return request.serializeBinary();
    },
    discord_token_pb.DiscordTokenGrpc.deserializeBinary
  );

  delete(
    request: discord_token_pb.DiscordTokenGrpc,
    metadata?: grpcWeb.Metadata | null): Promise<discord_token_pb.DiscordTokenGrpc>;

  delete(
    request: discord_token_pb.DiscordTokenGrpc,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: discord_token_pb.DiscordTokenGrpc) => void): grpcWeb.ClientReadableStream<discord_token_pb.DiscordTokenGrpc>;

  delete(
    request: discord_token_pb.DiscordTokenGrpc,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: discord_token_pb.DiscordTokenGrpc) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/DiscordToken.DiscordTokenGrpcService/Delete',
        request,
        metadata || {},
        this.methodDescriptorDelete,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/DiscordToken.DiscordTokenGrpcService/Delete',
    request,
    metadata || {},
    this.methodDescriptorDelete);
  }

  methodDescriptorDeleteBatch = new grpcWeb.MethodDescriptor(
    '/DiscordToken.DiscordTokenGrpcService/DeleteBatch',
    grpcWeb.MethodType.UNARY,
    discord_token_pb.DiscordTokenListGrpc,
    discord_token_pb.DiscordTokenResultGrpc,
    (request: discord_token_pb.DiscordTokenListGrpc) => {
      return request.serializeBinary();
    },
    discord_token_pb.DiscordTokenResultGrpc.deserializeBinary
  );

  deleteBatch(
    request: discord_token_pb.DiscordTokenListGrpc,
    metadata?: grpcWeb.Metadata | null): Promise<discord_token_pb.DiscordTokenResultGrpc>;

  deleteBatch(
    request: discord_token_pb.DiscordTokenListGrpc,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: discord_token_pb.DiscordTokenResultGrpc) => void): grpcWeb.ClientReadableStream<discord_token_pb.DiscordTokenResultGrpc>;

  deleteBatch(
    request: discord_token_pb.DiscordTokenListGrpc,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: discord_token_pb.DiscordTokenResultGrpc) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/DiscordToken.DiscordTokenGrpcService/DeleteBatch',
        request,
        metadata || {},
        this.methodDescriptorDeleteBatch,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/DiscordToken.DiscordTokenGrpcService/DeleteBatch',
    request,
    metadata || {},
    this.methodDescriptorDeleteBatch);
  }

}

