// source: discord_token.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

goog.exportSymbol('proto.DiscordToken.DiscordTokenGrpc', null, global);
goog.exportSymbol('proto.DiscordToken.DiscordTokenListGrpc', null, global);
goog.exportSymbol('proto.DiscordToken.DiscordTokenResultGrpc', null, global);
goog.exportSymbol('proto.DiscordToken.DiscordTokenSearchOptionsGrpc', null, global);
goog.exportSymbol('proto.DiscordToken.EditBatchRequestGrpc', null, global);
goog.exportSymbol('proto.DiscordToken.EditRequestGrpc', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.DiscordToken.DiscordTokenGrpc = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.DiscordToken.DiscordTokenGrpc, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.DiscordToken.DiscordTokenGrpc.displayName = 'proto.DiscordToken.DiscordTokenGrpc';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.DiscordToken.DiscordTokenSearchOptionsGrpc = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.DiscordToken.DiscordTokenSearchOptionsGrpc.repeatedFields_, null);
};
goog.inherits(proto.DiscordToken.DiscordTokenSearchOptionsGrpc, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.DiscordToken.DiscordTokenSearchOptionsGrpc.displayName = 'proto.DiscordToken.DiscordTokenSearchOptionsGrpc';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.DiscordToken.DiscordTokenListGrpc = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.DiscordToken.DiscordTokenListGrpc.repeatedFields_, null);
};
goog.inherits(proto.DiscordToken.DiscordTokenListGrpc, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.DiscordToken.DiscordTokenListGrpc.displayName = 'proto.DiscordToken.DiscordTokenListGrpc';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.DiscordToken.DiscordTokenResultGrpc = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.DiscordToken.DiscordTokenResultGrpc.repeatedFields_, null);
};
goog.inherits(proto.DiscordToken.DiscordTokenResultGrpc, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.DiscordToken.DiscordTokenResultGrpc.displayName = 'proto.DiscordToken.DiscordTokenResultGrpc';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.DiscordToken.EditRequestGrpc = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.DiscordToken.EditRequestGrpc.repeatedFields_, null);
};
goog.inherits(proto.DiscordToken.EditRequestGrpc, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.DiscordToken.EditRequestGrpc.displayName = 'proto.DiscordToken.EditRequestGrpc';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.DiscordToken.EditBatchRequestGrpc = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.DiscordToken.EditBatchRequestGrpc.repeatedFields_, null);
};
goog.inherits(proto.DiscordToken.EditBatchRequestGrpc, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.DiscordToken.EditBatchRequestGrpc.displayName = 'proto.DiscordToken.EditBatchRequestGrpc';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.DiscordToken.DiscordTokenGrpc.prototype.toObject = function(opt_includeInstance) {
  return proto.DiscordToken.DiscordTokenGrpc.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.DiscordToken.DiscordTokenGrpc} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.DiscordToken.DiscordTokenGrpc.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    userId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    name: jspb.Message.getFieldWithDefault(msg, 3, ""),
    token: jspb.Message.getFieldWithDefault(msg, 4, ""),
    updatedAt: jspb.Message.getFieldWithDefault(msg, 5, ""),
    createdAt: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.DiscordToken.DiscordTokenGrpc}
 */
proto.DiscordToken.DiscordTokenGrpc.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.DiscordToken.DiscordTokenGrpc;
  return proto.DiscordToken.DiscordTokenGrpc.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.DiscordToken.DiscordTokenGrpc} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.DiscordToken.DiscordTokenGrpc}
 */
proto.DiscordToken.DiscordTokenGrpc.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setToken(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setUpdatedAt(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setCreatedAt(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.DiscordToken.DiscordTokenGrpc.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.DiscordToken.DiscordTokenGrpc.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.DiscordToken.DiscordTokenGrpc} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.DiscordToken.DiscordTokenGrpc.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getUserId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getToken();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getUpdatedAt();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getCreatedAt();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.DiscordToken.DiscordTokenGrpc.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.DiscordToken.DiscordTokenGrpc} returns this
 */
proto.DiscordToken.DiscordTokenGrpc.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string user_id = 2;
 * @return {string}
 */
proto.DiscordToken.DiscordTokenGrpc.prototype.getUserId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.DiscordToken.DiscordTokenGrpc} returns this
 */
proto.DiscordToken.DiscordTokenGrpc.prototype.setUserId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string name = 3;
 * @return {string}
 */
proto.DiscordToken.DiscordTokenGrpc.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.DiscordToken.DiscordTokenGrpc} returns this
 */
proto.DiscordToken.DiscordTokenGrpc.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string token = 4;
 * @return {string}
 */
proto.DiscordToken.DiscordTokenGrpc.prototype.getToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.DiscordToken.DiscordTokenGrpc} returns this
 */
proto.DiscordToken.DiscordTokenGrpc.prototype.setToken = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string updated_at = 5;
 * @return {string}
 */
proto.DiscordToken.DiscordTokenGrpc.prototype.getUpdatedAt = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.DiscordToken.DiscordTokenGrpc} returns this
 */
proto.DiscordToken.DiscordTokenGrpc.prototype.setUpdatedAt = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string created_at = 6;
 * @return {string}
 */
proto.DiscordToken.DiscordTokenGrpc.prototype.getCreatedAt = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.DiscordToken.DiscordTokenGrpc} returns this
 */
proto.DiscordToken.DiscordTokenGrpc.prototype.setCreatedAt = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.DiscordToken.DiscordTokenSearchOptionsGrpc.repeatedFields_ = [1,2,3,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.DiscordToken.DiscordTokenSearchOptionsGrpc.prototype.toObject = function(opt_includeInstance) {
  return proto.DiscordToken.DiscordTokenSearchOptionsGrpc.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.DiscordToken.DiscordTokenSearchOptionsGrpc} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.DiscordToken.DiscordTokenSearchOptionsGrpc.toObject = function(includeInstance, msg) {
  var f, obj = {
    idsList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f,
    userIdsList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f,
    namesList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
    tokensList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.DiscordToken.DiscordTokenSearchOptionsGrpc}
 */
proto.DiscordToken.DiscordTokenSearchOptionsGrpc.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.DiscordToken.DiscordTokenSearchOptionsGrpc;
  return proto.DiscordToken.DiscordTokenSearchOptionsGrpc.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.DiscordToken.DiscordTokenSearchOptionsGrpc} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.DiscordToken.DiscordTokenSearchOptionsGrpc}
 */
proto.DiscordToken.DiscordTokenSearchOptionsGrpc.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addIds(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addUserIds(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addNames(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.addTokens(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.DiscordToken.DiscordTokenSearchOptionsGrpc.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.DiscordToken.DiscordTokenSearchOptionsGrpc.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.DiscordToken.DiscordTokenSearchOptionsGrpc} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.DiscordToken.DiscordTokenSearchOptionsGrpc.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIdsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
  f = message.getUserIdsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = message.getNamesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = message.getTokensList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      4,
      f
    );
  }
};


/**
 * repeated string ids = 1;
 * @return {!Array<string>}
 */
proto.DiscordToken.DiscordTokenSearchOptionsGrpc.prototype.getIdsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.DiscordToken.DiscordTokenSearchOptionsGrpc} returns this
 */
proto.DiscordToken.DiscordTokenSearchOptionsGrpc.prototype.setIdsList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.DiscordToken.DiscordTokenSearchOptionsGrpc} returns this
 */
proto.DiscordToken.DiscordTokenSearchOptionsGrpc.prototype.addIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.DiscordToken.DiscordTokenSearchOptionsGrpc} returns this
 */
proto.DiscordToken.DiscordTokenSearchOptionsGrpc.prototype.clearIdsList = function() {
  return this.setIdsList([]);
};


/**
 * repeated string user_ids = 2;
 * @return {!Array<string>}
 */
proto.DiscordToken.DiscordTokenSearchOptionsGrpc.prototype.getUserIdsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.DiscordToken.DiscordTokenSearchOptionsGrpc} returns this
 */
proto.DiscordToken.DiscordTokenSearchOptionsGrpc.prototype.setUserIdsList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.DiscordToken.DiscordTokenSearchOptionsGrpc} returns this
 */
proto.DiscordToken.DiscordTokenSearchOptionsGrpc.prototype.addUserIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.DiscordToken.DiscordTokenSearchOptionsGrpc} returns this
 */
proto.DiscordToken.DiscordTokenSearchOptionsGrpc.prototype.clearUserIdsList = function() {
  return this.setUserIdsList([]);
};


/**
 * repeated string names = 3;
 * @return {!Array<string>}
 */
proto.DiscordToken.DiscordTokenSearchOptionsGrpc.prototype.getNamesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.DiscordToken.DiscordTokenSearchOptionsGrpc} returns this
 */
proto.DiscordToken.DiscordTokenSearchOptionsGrpc.prototype.setNamesList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.DiscordToken.DiscordTokenSearchOptionsGrpc} returns this
 */
proto.DiscordToken.DiscordTokenSearchOptionsGrpc.prototype.addNames = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.DiscordToken.DiscordTokenSearchOptionsGrpc} returns this
 */
proto.DiscordToken.DiscordTokenSearchOptionsGrpc.prototype.clearNamesList = function() {
  return this.setNamesList([]);
};


/**
 * repeated string tokens = 4;
 * @return {!Array<string>}
 */
proto.DiscordToken.DiscordTokenSearchOptionsGrpc.prototype.getTokensList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 4));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.DiscordToken.DiscordTokenSearchOptionsGrpc} returns this
 */
proto.DiscordToken.DiscordTokenSearchOptionsGrpc.prototype.setTokensList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.DiscordToken.DiscordTokenSearchOptionsGrpc} returns this
 */
proto.DiscordToken.DiscordTokenSearchOptionsGrpc.prototype.addTokens = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.DiscordToken.DiscordTokenSearchOptionsGrpc} returns this
 */
proto.DiscordToken.DiscordTokenSearchOptionsGrpc.prototype.clearTokensList = function() {
  return this.setTokensList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.DiscordToken.DiscordTokenListGrpc.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.DiscordToken.DiscordTokenListGrpc.prototype.toObject = function(opt_includeInstance) {
  return proto.DiscordToken.DiscordTokenListGrpc.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.DiscordToken.DiscordTokenListGrpc} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.DiscordToken.DiscordTokenListGrpc.toObject = function(includeInstance, msg) {
  var f, obj = {
    itemsList: jspb.Message.toObjectList(msg.getItemsList(),
    proto.DiscordToken.DiscordTokenGrpc.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.DiscordToken.DiscordTokenListGrpc}
 */
proto.DiscordToken.DiscordTokenListGrpc.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.DiscordToken.DiscordTokenListGrpc;
  return proto.DiscordToken.DiscordTokenListGrpc.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.DiscordToken.DiscordTokenListGrpc} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.DiscordToken.DiscordTokenListGrpc}
 */
proto.DiscordToken.DiscordTokenListGrpc.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.DiscordToken.DiscordTokenGrpc;
      reader.readMessage(value,proto.DiscordToken.DiscordTokenGrpc.deserializeBinaryFromReader);
      msg.addItems(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.DiscordToken.DiscordTokenListGrpc.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.DiscordToken.DiscordTokenListGrpc.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.DiscordToken.DiscordTokenListGrpc} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.DiscordToken.DiscordTokenListGrpc.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getItemsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.DiscordToken.DiscordTokenGrpc.serializeBinaryToWriter
    );
  }
};


/**
 * repeated DiscordTokenGrpc items = 1;
 * @return {!Array<!proto.DiscordToken.DiscordTokenGrpc>}
 */
proto.DiscordToken.DiscordTokenListGrpc.prototype.getItemsList = function() {
  return /** @type{!Array<!proto.DiscordToken.DiscordTokenGrpc>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.DiscordToken.DiscordTokenGrpc, 1));
};


/**
 * @param {!Array<!proto.DiscordToken.DiscordTokenGrpc>} value
 * @return {!proto.DiscordToken.DiscordTokenListGrpc} returns this
*/
proto.DiscordToken.DiscordTokenListGrpc.prototype.setItemsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.DiscordToken.DiscordTokenGrpc=} opt_value
 * @param {number=} opt_index
 * @return {!proto.DiscordToken.DiscordTokenGrpc}
 */
proto.DiscordToken.DiscordTokenListGrpc.prototype.addItems = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.DiscordToken.DiscordTokenGrpc, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.DiscordToken.DiscordTokenListGrpc} returns this
 */
proto.DiscordToken.DiscordTokenListGrpc.prototype.clearItemsList = function() {
  return this.setItemsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.DiscordToken.DiscordTokenResultGrpc.repeatedFields_ = [1,2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.DiscordToken.DiscordTokenResultGrpc.prototype.toObject = function(opt_includeInstance) {
  return proto.DiscordToken.DiscordTokenResultGrpc.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.DiscordToken.DiscordTokenResultGrpc} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.DiscordToken.DiscordTokenResultGrpc.toObject = function(includeInstance, msg) {
  var f, obj = {
    itemsList: jspb.Message.toObjectList(msg.getItemsList(),
    proto.DiscordToken.DiscordTokenGrpc.toObject, includeInstance),
    errorsList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f,
    isSucceeded: jspb.Message.getBooleanFieldWithDefault(msg, 3, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.DiscordToken.DiscordTokenResultGrpc}
 */
proto.DiscordToken.DiscordTokenResultGrpc.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.DiscordToken.DiscordTokenResultGrpc;
  return proto.DiscordToken.DiscordTokenResultGrpc.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.DiscordToken.DiscordTokenResultGrpc} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.DiscordToken.DiscordTokenResultGrpc}
 */
proto.DiscordToken.DiscordTokenResultGrpc.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.DiscordToken.DiscordTokenGrpc;
      reader.readMessage(value,proto.DiscordToken.DiscordTokenGrpc.deserializeBinaryFromReader);
      msg.addItems(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addErrors(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsSucceeded(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.DiscordToken.DiscordTokenResultGrpc.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.DiscordToken.DiscordTokenResultGrpc.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.DiscordToken.DiscordTokenResultGrpc} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.DiscordToken.DiscordTokenResultGrpc.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getItemsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.DiscordToken.DiscordTokenGrpc.serializeBinaryToWriter
    );
  }
  f = message.getErrorsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = message.getIsSucceeded();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
};


/**
 * repeated DiscordTokenGrpc items = 1;
 * @return {!Array<!proto.DiscordToken.DiscordTokenGrpc>}
 */
proto.DiscordToken.DiscordTokenResultGrpc.prototype.getItemsList = function() {
  return /** @type{!Array<!proto.DiscordToken.DiscordTokenGrpc>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.DiscordToken.DiscordTokenGrpc, 1));
};


/**
 * @param {!Array<!proto.DiscordToken.DiscordTokenGrpc>} value
 * @return {!proto.DiscordToken.DiscordTokenResultGrpc} returns this
*/
proto.DiscordToken.DiscordTokenResultGrpc.prototype.setItemsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.DiscordToken.DiscordTokenGrpc=} opt_value
 * @param {number=} opt_index
 * @return {!proto.DiscordToken.DiscordTokenGrpc}
 */
proto.DiscordToken.DiscordTokenResultGrpc.prototype.addItems = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.DiscordToken.DiscordTokenGrpc, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.DiscordToken.DiscordTokenResultGrpc} returns this
 */
proto.DiscordToken.DiscordTokenResultGrpc.prototype.clearItemsList = function() {
  return this.setItemsList([]);
};


/**
 * repeated string errors = 2;
 * @return {!Array<string>}
 */
proto.DiscordToken.DiscordTokenResultGrpc.prototype.getErrorsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.DiscordToken.DiscordTokenResultGrpc} returns this
 */
proto.DiscordToken.DiscordTokenResultGrpc.prototype.setErrorsList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.DiscordToken.DiscordTokenResultGrpc} returns this
 */
proto.DiscordToken.DiscordTokenResultGrpc.prototype.addErrors = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.DiscordToken.DiscordTokenResultGrpc} returns this
 */
proto.DiscordToken.DiscordTokenResultGrpc.prototype.clearErrorsList = function() {
  return this.setErrorsList([]);
};


/**
 * optional bool is_succeeded = 3;
 * @return {boolean}
 */
proto.DiscordToken.DiscordTokenResultGrpc.prototype.getIsSucceeded = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.DiscordToken.DiscordTokenResultGrpc} returns this
 */
proto.DiscordToken.DiscordTokenResultGrpc.prototype.setIsSucceeded = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.DiscordToken.EditRequestGrpc.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.DiscordToken.EditRequestGrpc.prototype.toObject = function(opt_includeInstance) {
  return proto.DiscordToken.EditRequestGrpc.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.DiscordToken.EditRequestGrpc} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.DiscordToken.EditRequestGrpc.toObject = function(includeInstance, msg) {
  var f, obj = {
    target: (f = msg.getTarget()) && proto.DiscordToken.DiscordTokenGrpc.toObject(includeInstance, f),
    modify: (f = msg.getModify()) && proto.DiscordToken.DiscordTokenGrpc.toObject(includeInstance, f),
    overrideFieldsList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.DiscordToken.EditRequestGrpc}
 */
proto.DiscordToken.EditRequestGrpc.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.DiscordToken.EditRequestGrpc;
  return proto.DiscordToken.EditRequestGrpc.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.DiscordToken.EditRequestGrpc} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.DiscordToken.EditRequestGrpc}
 */
proto.DiscordToken.EditRequestGrpc.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.DiscordToken.DiscordTokenGrpc;
      reader.readMessage(value,proto.DiscordToken.DiscordTokenGrpc.deserializeBinaryFromReader);
      msg.setTarget(value);
      break;
    case 2:
      var value = new proto.DiscordToken.DiscordTokenGrpc;
      reader.readMessage(value,proto.DiscordToken.DiscordTokenGrpc.deserializeBinaryFromReader);
      msg.setModify(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addOverrideFields(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.DiscordToken.EditRequestGrpc.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.DiscordToken.EditRequestGrpc.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.DiscordToken.EditRequestGrpc} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.DiscordToken.EditRequestGrpc.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTarget();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.DiscordToken.DiscordTokenGrpc.serializeBinaryToWriter
    );
  }
  f = message.getModify();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.DiscordToken.DiscordTokenGrpc.serializeBinaryToWriter
    );
  }
  f = message.getOverrideFieldsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
};


/**
 * optional DiscordTokenGrpc target = 1;
 * @return {?proto.DiscordToken.DiscordTokenGrpc}
 */
proto.DiscordToken.EditRequestGrpc.prototype.getTarget = function() {
  return /** @type{?proto.DiscordToken.DiscordTokenGrpc} */ (
    jspb.Message.getWrapperField(this, proto.DiscordToken.DiscordTokenGrpc, 1));
};


/**
 * @param {?proto.DiscordToken.DiscordTokenGrpc|undefined} value
 * @return {!proto.DiscordToken.EditRequestGrpc} returns this
*/
proto.DiscordToken.EditRequestGrpc.prototype.setTarget = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.DiscordToken.EditRequestGrpc} returns this
 */
proto.DiscordToken.EditRequestGrpc.prototype.clearTarget = function() {
  return this.setTarget(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.DiscordToken.EditRequestGrpc.prototype.hasTarget = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional DiscordTokenGrpc modify = 2;
 * @return {?proto.DiscordToken.DiscordTokenGrpc}
 */
proto.DiscordToken.EditRequestGrpc.prototype.getModify = function() {
  return /** @type{?proto.DiscordToken.DiscordTokenGrpc} */ (
    jspb.Message.getWrapperField(this, proto.DiscordToken.DiscordTokenGrpc, 2));
};


/**
 * @param {?proto.DiscordToken.DiscordTokenGrpc|undefined} value
 * @return {!proto.DiscordToken.EditRequestGrpc} returns this
*/
proto.DiscordToken.EditRequestGrpc.prototype.setModify = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.DiscordToken.EditRequestGrpc} returns this
 */
proto.DiscordToken.EditRequestGrpc.prototype.clearModify = function() {
  return this.setModify(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.DiscordToken.EditRequestGrpc.prototype.hasModify = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated string override_fields = 3;
 * @return {!Array<string>}
 */
proto.DiscordToken.EditRequestGrpc.prototype.getOverrideFieldsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.DiscordToken.EditRequestGrpc} returns this
 */
proto.DiscordToken.EditRequestGrpc.prototype.setOverrideFieldsList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.DiscordToken.EditRequestGrpc} returns this
 */
proto.DiscordToken.EditRequestGrpc.prototype.addOverrideFields = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.DiscordToken.EditRequestGrpc} returns this
 */
proto.DiscordToken.EditRequestGrpc.prototype.clearOverrideFieldsList = function() {
  return this.setOverrideFieldsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.DiscordToken.EditBatchRequestGrpc.repeatedFields_ = [1,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.DiscordToken.EditBatchRequestGrpc.prototype.toObject = function(opt_includeInstance) {
  return proto.DiscordToken.EditBatchRequestGrpc.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.DiscordToken.EditBatchRequestGrpc} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.DiscordToken.EditBatchRequestGrpc.toObject = function(includeInstance, msg) {
  var f, obj = {
    targetsList: jspb.Message.toObjectList(msg.getTargetsList(),
    proto.DiscordToken.DiscordTokenGrpc.toObject, includeInstance),
    modify: (f = msg.getModify()) && proto.DiscordToken.DiscordTokenGrpc.toObject(includeInstance, f),
    overrideFieldsList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.DiscordToken.EditBatchRequestGrpc}
 */
proto.DiscordToken.EditBatchRequestGrpc.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.DiscordToken.EditBatchRequestGrpc;
  return proto.DiscordToken.EditBatchRequestGrpc.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.DiscordToken.EditBatchRequestGrpc} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.DiscordToken.EditBatchRequestGrpc}
 */
proto.DiscordToken.EditBatchRequestGrpc.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.DiscordToken.DiscordTokenGrpc;
      reader.readMessage(value,proto.DiscordToken.DiscordTokenGrpc.deserializeBinaryFromReader);
      msg.addTargets(value);
      break;
    case 2:
      var value = new proto.DiscordToken.DiscordTokenGrpc;
      reader.readMessage(value,proto.DiscordToken.DiscordTokenGrpc.deserializeBinaryFromReader);
      msg.setModify(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addOverrideFields(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.DiscordToken.EditBatchRequestGrpc.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.DiscordToken.EditBatchRequestGrpc.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.DiscordToken.EditBatchRequestGrpc} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.DiscordToken.EditBatchRequestGrpc.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTargetsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.DiscordToken.DiscordTokenGrpc.serializeBinaryToWriter
    );
  }
  f = message.getModify();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.DiscordToken.DiscordTokenGrpc.serializeBinaryToWriter
    );
  }
  f = message.getOverrideFieldsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
};


/**
 * repeated DiscordTokenGrpc targets = 1;
 * @return {!Array<!proto.DiscordToken.DiscordTokenGrpc>}
 */
proto.DiscordToken.EditBatchRequestGrpc.prototype.getTargetsList = function() {
  return /** @type{!Array<!proto.DiscordToken.DiscordTokenGrpc>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.DiscordToken.DiscordTokenGrpc, 1));
};


/**
 * @param {!Array<!proto.DiscordToken.DiscordTokenGrpc>} value
 * @return {!proto.DiscordToken.EditBatchRequestGrpc} returns this
*/
proto.DiscordToken.EditBatchRequestGrpc.prototype.setTargetsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.DiscordToken.DiscordTokenGrpc=} opt_value
 * @param {number=} opt_index
 * @return {!proto.DiscordToken.DiscordTokenGrpc}
 */
proto.DiscordToken.EditBatchRequestGrpc.prototype.addTargets = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.DiscordToken.DiscordTokenGrpc, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.DiscordToken.EditBatchRequestGrpc} returns this
 */
proto.DiscordToken.EditBatchRequestGrpc.prototype.clearTargetsList = function() {
  return this.setTargetsList([]);
};


/**
 * optional DiscordTokenGrpc modify = 2;
 * @return {?proto.DiscordToken.DiscordTokenGrpc}
 */
proto.DiscordToken.EditBatchRequestGrpc.prototype.getModify = function() {
  return /** @type{?proto.DiscordToken.DiscordTokenGrpc} */ (
    jspb.Message.getWrapperField(this, proto.DiscordToken.DiscordTokenGrpc, 2));
};


/**
 * @param {?proto.DiscordToken.DiscordTokenGrpc|undefined} value
 * @return {!proto.DiscordToken.EditBatchRequestGrpc} returns this
*/
proto.DiscordToken.EditBatchRequestGrpc.prototype.setModify = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.DiscordToken.EditBatchRequestGrpc} returns this
 */
proto.DiscordToken.EditBatchRequestGrpc.prototype.clearModify = function() {
  return this.setModify(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.DiscordToken.EditBatchRequestGrpc.prototype.hasModify = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated string override_fields = 3;
 * @return {!Array<string>}
 */
proto.DiscordToken.EditBatchRequestGrpc.prototype.getOverrideFieldsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.DiscordToken.EditBatchRequestGrpc} returns this
 */
proto.DiscordToken.EditBatchRequestGrpc.prototype.setOverrideFieldsList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.DiscordToken.EditBatchRequestGrpc} returns this
 */
proto.DiscordToken.EditBatchRequestGrpc.prototype.addOverrideFields = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.DiscordToken.EditBatchRequestGrpc} returns this
 */
proto.DiscordToken.EditBatchRequestGrpc.prototype.clearOverrideFieldsList = function() {
  return this.setOverrideFieldsList([]);
};


goog.object.extend(exports, proto.DiscordToken);
