/**
 * @fileoverview gRPC-Web generated client stub for DiscordToken
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.20.3
// source: discord_token.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.DiscordToken = require('./discord_token_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.DiscordToken.DiscordTokenGrpcServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.DiscordToken.DiscordTokenGrpcServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.DiscordToken.DiscordTokenSearchOptionsGrpc,
 *   !proto.DiscordToken.DiscordTokenListGrpc>}
 */
const methodDescriptor_DiscordTokenGrpcService_Get = new grpc.web.MethodDescriptor(
  '/DiscordToken.DiscordTokenGrpcService/Get',
  grpc.web.MethodType.UNARY,
  proto.DiscordToken.DiscordTokenSearchOptionsGrpc,
  proto.DiscordToken.DiscordTokenListGrpc,
  /**
   * @param {!proto.DiscordToken.DiscordTokenSearchOptionsGrpc} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.DiscordToken.DiscordTokenListGrpc.deserializeBinary
);


/**
 * @param {!proto.DiscordToken.DiscordTokenSearchOptionsGrpc} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.DiscordToken.DiscordTokenListGrpc)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.DiscordToken.DiscordTokenListGrpc>|undefined}
 *     The XHR Node Readable Stream
 */
proto.DiscordToken.DiscordTokenGrpcServiceClient.prototype.get =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/DiscordToken.DiscordTokenGrpcService/Get',
      request,
      metadata || {},
      methodDescriptor_DiscordTokenGrpcService_Get,
      callback);
};


/**
 * @param {!proto.DiscordToken.DiscordTokenSearchOptionsGrpc} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.DiscordToken.DiscordTokenListGrpc>}
 *     Promise that resolves to the response
 */
proto.DiscordToken.DiscordTokenGrpcServicePromiseClient.prototype.get =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/DiscordToken.DiscordTokenGrpcService/Get',
      request,
      metadata || {},
      methodDescriptor_DiscordTokenGrpcService_Get);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.DiscordToken.DiscordTokenGrpc,
 *   !proto.DiscordToken.DiscordTokenGrpc>}
 */
const methodDescriptor_DiscordTokenGrpcService_Create = new grpc.web.MethodDescriptor(
  '/DiscordToken.DiscordTokenGrpcService/Create',
  grpc.web.MethodType.UNARY,
  proto.DiscordToken.DiscordTokenGrpc,
  proto.DiscordToken.DiscordTokenGrpc,
  /**
   * @param {!proto.DiscordToken.DiscordTokenGrpc} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.DiscordToken.DiscordTokenGrpc.deserializeBinary
);


/**
 * @param {!proto.DiscordToken.DiscordTokenGrpc} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.DiscordToken.DiscordTokenGrpc)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.DiscordToken.DiscordTokenGrpc>|undefined}
 *     The XHR Node Readable Stream
 */
proto.DiscordToken.DiscordTokenGrpcServiceClient.prototype.create =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/DiscordToken.DiscordTokenGrpcService/Create',
      request,
      metadata || {},
      methodDescriptor_DiscordTokenGrpcService_Create,
      callback);
};


/**
 * @param {!proto.DiscordToken.DiscordTokenGrpc} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.DiscordToken.DiscordTokenGrpc>}
 *     Promise that resolves to the response
 */
proto.DiscordToken.DiscordTokenGrpcServicePromiseClient.prototype.create =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/DiscordToken.DiscordTokenGrpcService/Create',
      request,
      metadata || {},
      methodDescriptor_DiscordTokenGrpcService_Create);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.DiscordToken.DiscordTokenListGrpc,
 *   !proto.DiscordToken.DiscordTokenResultGrpc>}
 */
const methodDescriptor_DiscordTokenGrpcService_CreateBatch = new grpc.web.MethodDescriptor(
  '/DiscordToken.DiscordTokenGrpcService/CreateBatch',
  grpc.web.MethodType.UNARY,
  proto.DiscordToken.DiscordTokenListGrpc,
  proto.DiscordToken.DiscordTokenResultGrpc,
  /**
   * @param {!proto.DiscordToken.DiscordTokenListGrpc} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.DiscordToken.DiscordTokenResultGrpc.deserializeBinary
);


/**
 * @param {!proto.DiscordToken.DiscordTokenListGrpc} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.DiscordToken.DiscordTokenResultGrpc)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.DiscordToken.DiscordTokenResultGrpc>|undefined}
 *     The XHR Node Readable Stream
 */
proto.DiscordToken.DiscordTokenGrpcServiceClient.prototype.createBatch =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/DiscordToken.DiscordTokenGrpcService/CreateBatch',
      request,
      metadata || {},
      methodDescriptor_DiscordTokenGrpcService_CreateBatch,
      callback);
};


/**
 * @param {!proto.DiscordToken.DiscordTokenListGrpc} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.DiscordToken.DiscordTokenResultGrpc>}
 *     Promise that resolves to the response
 */
proto.DiscordToken.DiscordTokenGrpcServicePromiseClient.prototype.createBatch =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/DiscordToken.DiscordTokenGrpcService/CreateBatch',
      request,
      metadata || {},
      methodDescriptor_DiscordTokenGrpcService_CreateBatch);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.DiscordToken.EditRequestGrpc,
 *   !proto.DiscordToken.DiscordTokenGrpc>}
 */
const methodDescriptor_DiscordTokenGrpcService_Edit = new grpc.web.MethodDescriptor(
  '/DiscordToken.DiscordTokenGrpcService/Edit',
  grpc.web.MethodType.UNARY,
  proto.DiscordToken.EditRequestGrpc,
  proto.DiscordToken.DiscordTokenGrpc,
  /**
   * @param {!proto.DiscordToken.EditRequestGrpc} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.DiscordToken.DiscordTokenGrpc.deserializeBinary
);


/**
 * @param {!proto.DiscordToken.EditRequestGrpc} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.DiscordToken.DiscordTokenGrpc)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.DiscordToken.DiscordTokenGrpc>|undefined}
 *     The XHR Node Readable Stream
 */
proto.DiscordToken.DiscordTokenGrpcServiceClient.prototype.edit =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/DiscordToken.DiscordTokenGrpcService/Edit',
      request,
      metadata || {},
      methodDescriptor_DiscordTokenGrpcService_Edit,
      callback);
};


/**
 * @param {!proto.DiscordToken.EditRequestGrpc} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.DiscordToken.DiscordTokenGrpc>}
 *     Promise that resolves to the response
 */
proto.DiscordToken.DiscordTokenGrpcServicePromiseClient.prototype.edit =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/DiscordToken.DiscordTokenGrpcService/Edit',
      request,
      metadata || {},
      methodDescriptor_DiscordTokenGrpcService_Edit);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.DiscordToken.EditBatchRequestGrpc,
 *   !proto.DiscordToken.DiscordTokenResultGrpc>}
 */
const methodDescriptor_DiscordTokenGrpcService_EditBatch = new grpc.web.MethodDescriptor(
  '/DiscordToken.DiscordTokenGrpcService/EditBatch',
  grpc.web.MethodType.UNARY,
  proto.DiscordToken.EditBatchRequestGrpc,
  proto.DiscordToken.DiscordTokenResultGrpc,
  /**
   * @param {!proto.DiscordToken.EditBatchRequestGrpc} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.DiscordToken.DiscordTokenResultGrpc.deserializeBinary
);


/**
 * @param {!proto.DiscordToken.EditBatchRequestGrpc} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.DiscordToken.DiscordTokenResultGrpc)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.DiscordToken.DiscordTokenResultGrpc>|undefined}
 *     The XHR Node Readable Stream
 */
proto.DiscordToken.DiscordTokenGrpcServiceClient.prototype.editBatch =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/DiscordToken.DiscordTokenGrpcService/EditBatch',
      request,
      metadata || {},
      methodDescriptor_DiscordTokenGrpcService_EditBatch,
      callback);
};


/**
 * @param {!proto.DiscordToken.EditBatchRequestGrpc} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.DiscordToken.DiscordTokenResultGrpc>}
 *     Promise that resolves to the response
 */
proto.DiscordToken.DiscordTokenGrpcServicePromiseClient.prototype.editBatch =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/DiscordToken.DiscordTokenGrpcService/EditBatch',
      request,
      metadata || {},
      methodDescriptor_DiscordTokenGrpcService_EditBatch);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.DiscordToken.DiscordTokenGrpc,
 *   !proto.DiscordToken.DiscordTokenGrpc>}
 */
const methodDescriptor_DiscordTokenGrpcService_Delete = new grpc.web.MethodDescriptor(
  '/DiscordToken.DiscordTokenGrpcService/Delete',
  grpc.web.MethodType.UNARY,
  proto.DiscordToken.DiscordTokenGrpc,
  proto.DiscordToken.DiscordTokenGrpc,
  /**
   * @param {!proto.DiscordToken.DiscordTokenGrpc} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.DiscordToken.DiscordTokenGrpc.deserializeBinary
);


/**
 * @param {!proto.DiscordToken.DiscordTokenGrpc} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.DiscordToken.DiscordTokenGrpc)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.DiscordToken.DiscordTokenGrpc>|undefined}
 *     The XHR Node Readable Stream
 */
proto.DiscordToken.DiscordTokenGrpcServiceClient.prototype.delete =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/DiscordToken.DiscordTokenGrpcService/Delete',
      request,
      metadata || {},
      methodDescriptor_DiscordTokenGrpcService_Delete,
      callback);
};


/**
 * @param {!proto.DiscordToken.DiscordTokenGrpc} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.DiscordToken.DiscordTokenGrpc>}
 *     Promise that resolves to the response
 */
proto.DiscordToken.DiscordTokenGrpcServicePromiseClient.prototype.delete =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/DiscordToken.DiscordTokenGrpcService/Delete',
      request,
      metadata || {},
      methodDescriptor_DiscordTokenGrpcService_Delete);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.DiscordToken.DiscordTokenListGrpc,
 *   !proto.DiscordToken.DiscordTokenResultGrpc>}
 */
const methodDescriptor_DiscordTokenGrpcService_DeleteBatch = new grpc.web.MethodDescriptor(
  '/DiscordToken.DiscordTokenGrpcService/DeleteBatch',
  grpc.web.MethodType.UNARY,
  proto.DiscordToken.DiscordTokenListGrpc,
  proto.DiscordToken.DiscordTokenResultGrpc,
  /**
   * @param {!proto.DiscordToken.DiscordTokenListGrpc} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.DiscordToken.DiscordTokenResultGrpc.deserializeBinary
);


/**
 * @param {!proto.DiscordToken.DiscordTokenListGrpc} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.DiscordToken.DiscordTokenResultGrpc)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.DiscordToken.DiscordTokenResultGrpc>|undefined}
 *     The XHR Node Readable Stream
 */
proto.DiscordToken.DiscordTokenGrpcServiceClient.prototype.deleteBatch =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/DiscordToken.DiscordTokenGrpcService/DeleteBatch',
      request,
      metadata || {},
      methodDescriptor_DiscordTokenGrpcService_DeleteBatch,
      callback);
};


/**
 * @param {!proto.DiscordToken.DiscordTokenListGrpc} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.DiscordToken.DiscordTokenResultGrpc>}
 *     Promise that resolves to the response
 */
proto.DiscordToken.DiscordTokenGrpcServicePromiseClient.prototype.deleteBatch =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/DiscordToken.DiscordTokenGrpcService/DeleteBatch',
      request,
      metadata || {},
      methodDescriptor_DiscordTokenGrpcService_DeleteBatch);
};


module.exports = proto.DiscordToken;

